Add missing h5 and h6 methods to DomBuilder
- Added h5() static method to create <h5> elements
- Added h6() static method to create <h6> elements
- These heading levels were used in NodeListView but not defined in DomBuilder
- Fixes runtime error: "(intermediate value).h5 is not a function"